from __future__ import annotations

import scripts.create_release_record as release_record


def test_create_release_record_writes_expected_markdown(tmp_path, monkeypatch):
    monkeypatch.setattr(release_record, "OUTPUT_DIR", tmp_path)
    monkeypatch.setattr(
        release_record,
        "_build_record",
        lambda version, environment, operator, commit_ref, **_: "\n".join(
            [
                "# Release Record",
                f"- Version: {version}",
                f"- Operator: {operator}",
                f"- Commit / tag: {commit_ref}",
                f"- Environment: {environment}",
                "",
            ]
        ),
    )

    output_path = release_record.create_release_record(
        version="1.2.3",
        environment="staging",
        operator="alice",
        commit_ref="abc1234",
    )

    assert output_path == tmp_path / "1.2.3-staging.md"
    assert output_path.exists()
    text = output_path.read_text(encoding="utf-8")
    assert "- Version: 1.2.3" in text
    assert "- Operator: alice" in text
    assert "- Commit / tag: abc1234" in text
    assert "- Environment: staging" in text


def test_build_record_includes_generated_header(monkeypatch, tmp_path):
    template = tmp_path / "release_log_template.md"
    template.write_text(
        "# Release Record\n\n## Change Summary\n\n- \n",
        encoding="utf-8",
    )
    monkeypatch.setattr(release_record, "TEMPLATE_FILE", template)

    text = release_record._build_record(
        version="9.9.9",
        environment="prod",
        operator="ops",
        commit_ref="deadbee",
    )

    assert text.startswith("# Release Record")
    assert "- Version: 9.9.9" in text
    assert "- Environment: prod" in text
    assert "- Operator: ops" in text
    assert "- Commit / tag: deadbee" in text
    assert "Generated by scripts/create_release_record.py" in text
    assert "## Change Summary" in text


def test_build_record_includes_release_evidence_fields(monkeypatch, tmp_path):
    template = tmp_path / "release_log_template.md"
    smoke_file = tmp_path / "post_release_smoke_test.txt"
    snapshot_file = tmp_path / "runtime_snapshot.txt"
    smoke_file.write_text("ok", encoding="utf-8")
    snapshot_file.write_text("ok", encoding="utf-8")
    template.write_text(
        "\n".join(
            [
                "# Release Record",
                "",
                "## Change Summary",
                "",
                "- ",
                "",
                "## Deployment Steps",
                "",
                "- [ ] `scripts/post_release_smoke_test.sh` captured",
                "- [ ] `scripts/collect_runtime_snapshot.sh` captured",
                "",
                "## Monitoring Trace",
                "",
                "- Health check request ID:",
                "- Smoke test file / command output link:",
                "- Snapshot file / command output link:",
                "- Scheduled health probe log excerpt:",
                "- Alert log excerpt (`journalctl -t personal_library_alert`):",
                "- Related issue / feedback links:",
            ]
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(release_record, "TEMPLATE_FILE", template)

    text = release_record._build_record(
        version="9.9.9",
        environment="prod",
        operator="ops",
        commit_ref="deadbee",
        health_request_id="req-123",
        smoke_file=smoke_file,
        snapshot_file=snapshot_file,
        scheduled_health_log="journalctl -u personal_library-healthcheck.service -n 20",
        alert_log_ref="journalctl -t personal_library_alert -n 20",
        related_links="issue/123",
    )

    assert "- [x] `scripts/post_release_smoke_test.sh` captured" in text
    assert "- [x] `scripts/collect_runtime_snapshot.sh` captured" in text
    assert "- Health check request ID: req-123" in text
    assert "post_release_smoke_test.txt" in text
    assert "runtime_snapshot.txt" in text
    assert "personal_library-healthcheck.service" in text
    assert "personal_library_alert" in text
    assert "- Related issue / feedback links: issue/123" in text


def test_create_release_record_resolves_evidence_dir(tmp_path, monkeypatch):
    monkeypatch.setattr(release_record, "OUTPUT_DIR", tmp_path / "records")

    evidence_dir = tmp_path / "evidence"
    evidence_dir.mkdir()
    (evidence_dir / "post_release_smoke_test.txt").write_text("ok", encoding="utf-8")
    (evidence_dir / "runtime_snapshot.txt").write_text("ok", encoding="utf-8")

    captured: dict[str, object] = {}

    def fake_build_record(version, environment, operator, commit_ref, **kwargs):
        captured["version"] = version
        captured["environment"] = environment
        captured["operator"] = operator
        captured["commit_ref"] = commit_ref
        captured.update(kwargs)
        return "# Release Record\n"

    monkeypatch.setattr(release_record, "_build_record", fake_build_record)

    output_path = release_record.create_release_record(
        version="1.2.3",
        environment="prod",
        operator="alice",
        commit_ref="abc1234",
        evidence_dir=str(evidence_dir),
    )

    assert output_path == tmp_path / "records" / "1.2.3-prod.md"
    assert captured["smoke_file"] == evidence_dir / "post_release_smoke_test.txt"
    assert captured["snapshot_file"] == evidence_dir / "runtime_snapshot.txt"


def test_create_release_record_extracts_request_id_from_evidence(tmp_path, monkeypatch):
    monkeypatch.setattr(release_record, "OUTPUT_DIR", tmp_path / "records")

    evidence_dir = tmp_path / "evidence"
    evidence_dir.mkdir()
    (evidence_dir / "post_release_smoke_test.txt").write_text(
        "request_id=smoke-123\n",
        encoding="utf-8",
    )
    (evidence_dir / "runtime_snapshot.txt").write_text(
        "request_id=snapshot-456\n",
        encoding="utf-8",
    )

    captured: dict[str, object] = {}

    def fake_build_record(version, environment, operator, commit_ref, **kwargs):
        captured.update(kwargs)
        return "# Release Record\n"

    monkeypatch.setattr(release_record, "_build_record", fake_build_record)

    release_record.create_release_record(
        version="1.2.3",
        environment="prod",
        operator="alice",
        commit_ref="abc1234",
        evidence_dir=str(evidence_dir),
    )

    assert captured["health_request_id"] == "snapshot-456"
